name: Node.js CI Pipeline

on: # when will script run
  push: 
    branches:
      - main

jobs: # can contain multiple jobs
  build-and-test: # jo b name 
    # job runs on ubuntu server
    runs-on: ubuntu-latest # creates temporary ubuntu machine which will be deleted after running all commands

    steps:
      # Download repository code
      - name: Checkout Code
        uses: actions/checkout@v4 # prebuilt GitHub Action. download code in ubuntu machine

      # Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Run Vitest tests
      - name: Run Unit Tests
        run: npm test

      # Verify Docker image builds successfully
      - name: Test Docker Build
        run: docker build -t todo-app .